### ISSUE TITLE
When reseting project filters take into account which page is being displayed

### ISSUE THREAD

**Issue by alereca** [team120/Universiteams-front#129]

**Comment by alereca** [comment]
When reseting filters in "My Projects" page (`http://localhost:3000/projects?requestState=Accepted&requestState=Kicked&sortBy=requestEnrollmentCount&inAscendingOrder=false`) it redirects to Base Projects page (`http://localhost:3000/projects`) instead of going back to "My Projects" page

**Comment by alereca** [comment]
Since all pages are in fact the same one but using different params is impossible to reset form filters

Consequently we will have to divide it into multiple pages to support this, for example:
- /projects/mine
- /projects/requests
- /projects/favorite
- /projects

**Comment by alereca** [comment]
The main issue may be in reset onClick handler

**Comment by alereca** [comment]
When clicking on reset even `generalSearch` query string is being cleared. Resetting should only update url query params from project filters

**Comment by JAcciarri** [comment]
Exactly! Awesome
