### ISSUE TITLE
Admin page (Unified CRUD for Institutions, Facilities, Departments, Users)

### ISSUE THREAD

**Issue by NicoAntonelli** [team120/Universiteams-front#22]

**Comment by alereca** [comment]
Backend part: https://github.com/team120/Universiteams/issues/134

**Comment by alereca** [comment]
Mantine React Table reference:
- - https://v2.mantine-react-table.com/docs/examples/advanced
- https://v2.mantine-react-table.com/docs/guides/row-selection#read-row-selection-state-or-rows-from-table-instance
- https://v2.mantine-react-table.com/docs/examples/editing-crud
